### ISSUE TITLE
[UI] UI requirements

### ISSUE THREAD

**Issue by SzymonSt** [Signal0ne/signal0ne-vscode-extension#11]
- [x] If no issue is displayed, show proper message
- [x] Remove "Focus issue" button, focus issue and show issue details if tree item is clicked and selected (tree view item changes the background to gray)
- [x] User should be able to completely deselect all issues(no focused issue)

**Comment by SzymonSt** [comment]
@Paweleksltzn @MRadzynski just pinging to not to forget about these requirement

**Comment by MRadzynski** [comment]
- [x] We need to improve the formatting, the list should items should be in separate lines and the code snippets should be formatted 

<img width="361" alt="Screenshot 2024-05-18 at 23 04 45" src="https://github.com/Signal0ne/signal0ne-vscode-extension/assets/68923217/2d065be6-94b8-4204-90b7-df7c1e61cb5d">

**Comment by SzymonSt** [comment]
- [x] We need to improve formatting for `proposedCodeSolutionView.ts`
